### ISSUE TITLE
OpenFST does not recognize FST type "vector"

### ISSUE THREAD

**Issue by wincentbalin** [wincentbalin/compile-static-openfst#1]
`fstinfo.exe` does not recognize FST type `vector` when executed like that:

```
fstcompile.exe --isymbols=test.symbols --osymbols=test.symbols --keep_isymbols --keep_osymbols --acceptor test.txt | fstinfo
```

> ERROR: MutableFst::Read: Unknown FST type "vector" (arc type = "standard"): standard input

The files `test.txt` and `test.symbols` are attached (rename `test.symbols.txt` to `test.symbols`):

[test.txt](https://github.com/wincentbalin/compile-static-openfst/files/2024206/test.txt)
[test.symbols.txt](https://github.com/wincentbalin/compile-static-openfst/files/2024208/test.symbols.txt)

**Comment by wincentbalin** [comment]
The bug was reported by Roland F. Schwarz when compiling OpenFST in Cygwin. Subsequent test with the releases from this repository confirmed the bug in OpenFST versions 1.6.6 and 1.6.7 and the lack thereof in OpenFST version 1.6.5.

**Comment by wincentbalin** [comment]
Still exists in OpenFST 1.6.8.

**Comment by sergy5** [comment]
Is there a way to avoid this bug?

**Comment by wincentbalin** [comment]
Current workaround is using OpenFST 1.6.5. Alas, the development repository for OpenFST is not open, so there is no way to localise the error using `git bisect` (or similar tools).

**Comment by lumpidu** [comment]
Resurrecting this.

I had the same issue when integrating thrax & openfst in an Android application. 

The reason for the original error message is that many - if not all - static initialization of the globals in OpenFst are not done. E.g. if you take a look into the file `src/lib/fst-types.cc`, you will see those:

```c++
namespace fst {

REGISTER_FST(VectorFst, StdArc);
REGISTER_FST(VectorFst, LogArc);
REGISTER_FST(VectorFst, Log64Arc);
...
```

Actually the first one of the above is causing the reported error, because it's simply missing from your library initialization. You can also test this e.g. via 

```sh
nm -C <your executable> | grep fst::VectorFst_StdArc_registerer
```

Which should give you some result if it's working correctly.

I finally got it working by linking the openfst & thrax libraries differently by enclosing them via -Wl,--whole-archive / -Wl,--no-whole-archive. This includes all symbols of the original lib into the executable/shared object. Otherwise most globals will be omitted. I have not worked with your port of OpenFst for Cygwin, but I assume it must be a similar reason.

**Comment by lumpidu** [comment]
For the record: What has changed in OpenFst between `1.6.5` and `1.6.6` amongst others probably causing the troubles, is that mentioned above static initializers have been refactored out from src/lib/fst.cc into an own file src/lib/fst-types.cc. This file contains only those intitializers and otherwise no code pulls them in.

I used the current OpenFst `1.8.1` & Thrax `1.3.6` and it works like a charm now.

**Comment by wincentbalin** [comment]
While the two above comments are extremely hepful, I did not have enough resources to implement the suggested solution with the `-Wl,--whole-archive` and `-Wl,--no-whole-archive` options.

I suggest everyone, who wants to run OpenFST/OpenGRM on Windows, to read the first part of the README in the current repository and to choose one of the options listed there.

This repository will be archived shortly.

**Comment by shine-xia** [comment]
> Resurrecting this.
> 
> I had the same issue when integrating thrax & openfst in an Android application.
> 
> The reason for the original error message is that many - if not all - static initialization of the globals in OpenFst are not done. E.g. if you take a look into the file `src/lib/fst-types.cc`, you will see those:
> 
> ```c++
> namespace fst {
> 
> REGISTER_FST(VectorFst, StdArc);
> REGISTER_FST(VectorFst, LogArc);
> REGISTER_FST(VectorFst, Log64Arc);
> ...
> ```
> 
> Actually the first one of the above is causing the reported error, because it's simply missing from your library initialization. You can also test this e.g. via
> 
> ```shell
> nm -C <your executable> | grep fst::VectorFst_StdArc_registerer
> ```
> 
> Which should give you some result if it's working correctly.
> 
> I finally got it working by linking the openfst & thrax libraries differently by enclosing them via -Wl,--whole-archive / -Wl,--no-whole-archive. This includes all symbols of the original lib into the executable/shared object. Otherwise most globals will be omitted. I have not worked with your port of OpenFst for Cygwin, but I assume it must be a similar reason.

Thanks a lot for your analysis and solution. It works.
